"""
patchnotes._scaffold
`patchnotes init` — starter changelog and CI workflow for new projects.
"""

from __future__ import annotations

import os
from typing import Optional

STARTER_CHANGELOG = """\
# Changelog

All notable changes to this project are documented in this file. The format
follows [Keep a Changelog](https://keepachangelog.com) and this project
adheres to [Semantic Versioning](https://semver.org).

## [Unreleased]

### Added

- Started tracking changes in this changelog
"""

STARTER_WORKFLOW = """\
# Validates the changelog on every PR that touches it, with inline
# annotations on offending lines. Generated by `patchnotes init --workflow`.
name: Validate changelog

on:
  pull_request:
    paths: ["{file}"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Londopy/patchnotes@v2
        with:
          file: {file}
          strict: "true"
"""


def starter_changelog(repo_url: Optional[str] = None) -> str:
    """The starter CHANGELOG.md content (strict-validation clean)."""
    text = STARTER_CHANGELOG
    if repo_url:
        text += f"\n[unreleased]: {repo_url.rstrip('/')}/commits\n"
    return text


def write_changelog(path: str, repo_url: Optional[str] = None) -> None:
    """Create a starter changelog; refuses to overwrite."""
    if os.path.exists(path):
        raise FileExistsError(
            f"{path} already exists — refusing to overwrite. "
            f"Run `patchnotes {path} validate` to check it instead."
        )
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(starter_changelog(repo_url))


def write_workflow(changelog_path: str) -> str:
    """Create .github/workflows/changelog.yml next to the repo root."""
    base = os.path.dirname(changelog_path) or "."
    wf_dir = os.path.join(base, ".github", "workflows")
    wf_path = os.path.join(wf_dir, "changelog.yml")
    if os.path.exists(wf_path):
        raise FileExistsError(f"{wf_path} already exists — refusing to overwrite.")
    os.makedirs(wf_dir, exist_ok=True)
    rel = os.path.basename(changelog_path)
    with open(wf_path, "w", encoding="utf-8") as fh:
        fh.write(STARTER_WORKFLOW.format(file=rel))
    return wf_path
